### ISSUE TITLE
Form Creator: multi select

### ISSUE THREAD

**Issue by MichaelRBond** [wvulibraries/mfcs#108]
When selecting a form to link to, the "select a field" option doesn't display after the form is updated. 

I do not believe it is saving the information. Because on the data creation side there are no options in the dropdown for new multiselect select fields being added. 

When viewing forms that were created previously, the options are in the dropdown. 

Same problem is ocuring with the dropdown field type.

**Comment by ddavisgraphics** [comment]
This was a save problem.  Fixed, but working on some tests.

**Comment by ddavisgraphics** [comment]
Fixed bug introduced in fixing the last version.
