### ISSUE TITLE
Frontend: File preview not displaying correctly

### ISSUE THREAD

**Issue by MichaelRBond** [wvulibraries/mfcs#138]
The originals all seem to be correct. 

However the converted and thumbnails are not. They are correct on the file system, so i think it is in the javascript processing that is being done. 

When yo have 3 items (looking at rock cards) the converted and thumbnail preview for the second is the first and the third is that of the second. 

so:
File_a -> correct
file_b -> converted displays file_a
file_c -> converted displays file_b

**Comment by ddavisgraphics** [comment]
Filepreview fixed.  Was specifically at the thumbnails and with naming.
