### ISSUE TITLE
Menu is getting too long to display as it is. 

### ISSUE THREAD

**Issue by MichaelRBond** [wvulibraries/mfcs#154]
Menu is starting to scroll (with its own scroll bar). 

Either need to rethink the menu or include some sort of other navigation on pages ... 

Maybe just changing the font size will work?

**Comment by timbroadwater** [comment]
The font size is already smaller than standard (1em/16px), so the only suggestion I would make is to make the **line-height: 0;** and eliminate the borders. FYI, this is deigning for a specific pixel size (which I assume is laptop) in an age of RWD.
