### ISSUE TITLE
Need to add reprocessing back in. 

### ISSUE THREAD

**Issue by MichaelRBond** [wvulibraries/mfcs#156]

**Comment by MichaelRBond** [comment]
Reprocessing is currently possible via database manipulation. We need to make it easy to do via the interface. 

The original interface was removed during testing of version 2.0 due to lack of time to develop the feature and moving away from a "process in real time" to "process via scheduled task"

Needs to be implemented as follows:
1. reprocess individual item
1. reprocess all items for a form
1. reprocess all items with modified times between a date range
1. reprocess all items for a project

Questions:
1. What should the interface look like?
1. Where should the "reprocess" button appear for an individual item?

i imagine the general interface would be a series of drop downs to select form/project/date range. 

For individual items, perhaps appear under "history" in the upper right hand menu for the item? Should it have a confirmation to reprocess it? should it be a javascript confirm (or modal) or a separate page? 

@ddavisgraphics  and @timbroadwater  please weigh in on the interface questions. thanks.

**Comment by ddavisgraphics** [comment]
What does re-processing do?  If it is specifically for the files and conversions then absolutely this would be a good feature to add back in for the general form owner / admin.

This can be done from a single reprocessing page that uses query strings, or from a button that makes an ajax call to an API or a combination of both.  I think the form would be easy to add another icon that creates this interaction through the API call.  The per file one can be done in the FileView setup.  The date range that seems like it would be more complicated and require its own page.

**Comment by MichaelRBond** [comment]
I've already started a github branch for it. 

yes, it just adds objects back into the processing table.
