### ISSUE TITLE
Styling the file obsolete page

### ISSUE THREAD

**Issue by MichaelRBond** [wvulibraries/mfcs#162]
/dashboard/obsolete/

**Comment by timbroadwater** [comment]
Do I need to make a specific file or type of file (i.e. .tiff) obsolete to results for http://localhost:8080/dashboard/obsolete/. How do I do that?

**Comment by MichaelRBond** [comment]
You'll need to run the following commands:
cd /vagrant/public_html/crons
sudo php checksum_insertCurrentFiles.php
sudo php system_information_filetypes.php

Normally those run on the command line. That will setup the base for all of the dashboard stuff. 

Then you can insert new obsolete types on this page:
http://localhost:8080/admin/obsoleteFileTypes/  (this is in the menu as well). 

I just inserted pdf to test with. i know there are 6 pdf files in their to see results with.

**Comment by MichaelRBond** [comment]
@ddavisgraphics should run those commands as well if he hasn't already.
