### ISSUE TITLE
Navigation creator not displaying correctly

### ISSUE THREAD

**Issue by PseudoAj** [wvulibraries/mfcs#168]
When trying to add the logout button the layout is displayed on the top corner as shown in screenshot. 
![screen shot 2016-02-15 at 9 58 13 am](https://cloud.githubusercontent.com/assets/3308051/13052158/4784e400-d3cb-11e5-9bc9-46575e3ff8f4.png)

**Comment by ddavisgraphics** [comment]
Can't Replicate can you describe the process to get this error.

**Comment by PseudoAj** [comment]
I was going through following process:
1. Opened form creator for one of the forms
2. Added the logout button
3. Clicked update navigation
4. Logout appears on top of the page; out of the navigation layout.

**Comment by ddavisgraphics** [comment]
Can't duplicate.
