### ISSUE TITLE
Adding new subject heading doesn't appear in dropdown

### ISSUE THREAD

**Issue by MichaelRBond** [wvulibraries/mfcs#175]
Two more users have commented that when adding a subject heading from the modal that it does not populate in the multi select on data entry. 

We need to get this fixed before friday.

**Comment by MichaelRBond** [comment]
This appears to be working now. 

Also, items that are edited appear immediate now too.

**Comment by ddavisgraphics** [comment]
I've also made some improvements in speed when adding one from AJAX in the branch I just made.
