### ISSUE TITLE
"Jump" tools don't work on listing page in firefox

### ISSUE THREAD

**Issue by MichaelRBond** [wvulibraries/mfcs#211]
The Jump to page, jump to IDNO, and number of objects per page don't work in firefox. 

They do work in Chrome.

**Comment by ddavisgraphics** [comment]
This is fixed.  Many of the event functions for that page were called like

```
function handler_jumpToPage(){
   event.preventDefault(); 
}
```

firefox is more picky on the JS that goes into functions if there is no event declared in the function it doesn't propagate one from the document ready as chrome does.  To make the functions correct simply added an event as a parameter to the functions.  

```
function handler_jumpToPage(event){
   event.preventDefault(); 
}
```
