### ISSUE TITLE
Form Permissions

### ISSUE THREAD

**Issue by MichaelRBond** [wvulibraries/mfcs#64]
When entering form permissions on a newly created form, they don't stick

**Comment by ddavisgraphics** [comment]
This is the same as with development.  We can handle this a few different ways.  My thoughts would be to forward over the form the actual form editor and complete actions from there.   The only problem would be how to get the ID of the form that was just submitted or published.  Do you know any nice ways to do this?

**Comment by ddavisgraphics** [comment]
Fixed this by created a refresh that happens one second after the form is processed.  Uses the sqlResult to get the ID of the effected query and forwards appropriately.
