### ISSUE TITLE
"Cancel Edit & Unlock object" shouldn't be visible on new object forms.

### ISSUE THREAD

**Issue by MichaelRBond** [wvulibraries/mfcs#70]
Verify that locks are working properly still.

**Comment by ddavisgraphics** [comment]
How are the locks supposed to work?  When I view an object on the edit object in data entry I get Object is locked by another user.  

If you unlock this object he previous opened version will not be submitted.

**Comment by ddavisgraphics** [comment]
This is all still functioning.  There was a closing tag missing from the if statement keeping all of the objects in view.  The syntax was also messed up in a few other areas this is fixed.
