### ISSUE TITLE
IDNO displaying on Create Object form, when set to manage by system

### ISSUE THREAD

**Issue by MichaelRBond** [wvulibraries/mfcs#71]
The IDNO field is displaying on the Create Object form. It should only display when the IDNO is managed by the user. 

This is currently working on mfcsdev and in production. this is a newly introduced issue.

**Comment by ddavisgraphics** [comment]
I can't replicate this bug.  Can you show me where this is displaying on yours?

**Comment by ddavisgraphics** [comment]
This might have been fixed in another fix.  I had the IDNO aspects backwards for form element reveals.
